server:
  port: 9102

spring:
  application:
    name: web-auth
  datasource:
    url: jdbc:mysql://localhost:3306/nas?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #Spring Boot 2.0 之后默认使用 hikari 作为数据库连接池。如果使用其他连接池需要引入相关包，然后对应的增加配置
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9

  redis:
    database: 2
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

management:
  endpoint:
    health:
      enabled: true
mybatis:
  typeAliasesPackage: org.konsy.**.model
  mapperLocations: classpath*:mapper/**/*.xml
  configLocation: classpath:mybatis-config.xml

logging:
  level:
    root: info

